use_frameworks!

platform :ios, '10.0'

target 'TAAuth_Example' do
  pod 'TAAuth', :path => '../'
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SVProgressHUD'

  target 'TAAuth_Tests' do
    inherit! :search_paths

    
  end
end
